name: Release
on:
  push:
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/changelog"
            "@semantic-release/release-notes-generator@10.0.3"
            "@semantic-release/git
            "@semantic-release/github
        env:
          GH_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
