name: Sync Files
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 14 * * MON"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@878d649c33c834dc1eff4c00f7fcf16bf281eb63 # v1.17.15 February 2022
        with:
          GH_PAT: ${{ secrets.GOOGLEMAPS_BOT_REPO_TOKEN }}
          GIT_EMAIL: "googlemaps-bot@google.com"
          GIT_USERNAME: "googlemaps-bot"
          COMMIT_PREFIX: "chore: "
          OVERWRITE_EXISTING_PR: true
          CONFIG_PATH: .github/sync-files.yml
          BRANCH_PREFIX: file-sync
          PR_LABELS: |
            file-sync
            automerge
